name: Windows release

on:
  release:
    types:
      - created

jobs:
  windows:
      name: Release
      runs-on: windows-latest
      env:
          RUNNER_OS: "windows"
          CI: "1"
      steps:
          - name: Checkout branch
            uses: actions/checkout@v3
          - name: Install latest Rust stable
            uses: actions-rs/toolchain@v1
            with:
              toolchain: stable
              target: x86_64-pc-windows-msvc
              override: true
              components: rustfmt, clippy
          - name: Cargo build
            shell: bash -l {0}
            run: cargo build -vv
          - name: Cargo publish
            shell: bash -l {0}
            run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}